CREATE TABLE IF NOT EXISTS players (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    createddate INTEGER NOT NULL,
    lastonline INTEGER NOT NULL,
    CONSTRAINT players_name_idx UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS games (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    date INTEGER NOT NULL,
    status INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS moves (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    gameid INTEGER NOT NULL,
    playerid INTEGER NOT NULL,
    idx INTEGER NOT NULL,
    move TEXT NOT NULL,
    date INTEGER NOT NULL,
    FOREIGN KEY(gameid) REFERENCES games(id),
    FOREIGN KEY(playerid) REFERENCES players(id)
);
