# Use the official tensorflow image as the base image
FROM tensorflow/tensorflow:latest-gpu

RUN pip install debugpy

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY ./game_server/requirements.txt ./game_server/
COPY ./ai_agent/requirements.txt ./ai_agent/

# Install the Python dependencies
RUN pip install --no-cache-dir pytest
RUN pip install --no-cache-dir -r ./game_server/requirements.txt
RUN pip install --no-cache-dir -r ./ai_agent/requirements.txt

# Copy the rest of the application code to the container
COPY ./common ./common
COPY ./game_server ./game_server
COPY ./ai_agent ./ai_agent
COPY ./tests ./tests

# Expose the gRPC server's port
EXPOSE 8080
# Expose the debugpy port
EXPOSE 5678

# Specify the command to run your application
CMD [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "pytest", "--collect-only", "tests/" ] 
